services:
  code-server:
    build: .
    image: code-server:latest
    container_name: code-server
    restart: unless-stopped
    command: /home/coder/workspace
    ports:
      - "${PORT:-8080}:8080"
    environment:
      - DOCKER_USER=${DOCKER_USER:-keepresearch}
    volumes:
      - ${WORKSPACE_PATH}:/home/coder/project
      - ./config/settings.json:/home/coder/.local/share/code-server/User/settings.json
      - ./config/argv.json:/home/coder/.local/share/code-server/User/argv.json
      - ./config/config.yaml:/home/coder/.config/code-server/config.yaml:ro
